/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Process */

#ifndef _Included_Process
#define _Included_Process
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Process
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Process_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
