/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class business_Process */

#ifndef _Included_business_Process
#define _Included_business_Process
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     business_Process
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_business_Process_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
